version: '3.3'
services:
  swagger-ui:
    environment:
      - API_URL=http://${DOMAIN}/api/v1/swagger/
  backend:
    environment:
      - 'JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root'
      - SERVER_HOST=http://${DOMAIN}
  celeryworker:
    environment:
      - RUN=celery worker -A app.worker -l info -Q main-queue -c 1
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
      - SERVER_HOST=http://${DOMAIN}
  backend-tests:
    environment:
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
